### ISSUE TITLE
No main class detected

### ISSUE THREAD

**Issue by Matthew1172** [danwatford/abc#1]
Imported this project into IntelliJ using:
JDK 17
Scala 2021.3.20
SBT 1.6.2
When I got to the SBT shell, I typed in
```run src/test/resources/pgh_session_tunebook.abc```
and I got the error:
```
[error] java.lang.RuntimeException: No main class detected.
[error]         at scala.sys.package$.error(package.scala:30)
```
I tried to specify the main class by adding this line to the bottom of the build.sbt file:
```Compile/mainClass := Some("com.foomoo.abc.app.TuneMatcher")```
But then I get another error:
```
[error] java.lang.ClassNotFoundException: com.foomoo.abc.app.TuneMatcher
[error]         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
```

**Comment by danwatford** [comment]
Hi @Matthew1172 ,

The project is quite out of date with respect to SBT and Scala, so I thought I'd use Docker to jog my memory and try running it for you.

I was able to run the TuneMatcher example using docker as follows:

```
cd ~/dev/floss/scala
git clone https://github.com/danwatford/abc.git
cd abc

docker pull mozilla/sbt

mkdir ~/.ivy2
mkdir ~/.sbt

docker run -it --rm -v ~/.ivy2:/root/.ivy2 -v ~/.sbt:/root/.sbt -v $PWD:/app -w /app mozilla/sbt sbt shell

project abc-app
run parser/src/test/resources/pgh_session_tunebook.abc
```


The key was to tell sbt which project to use when looking for a main class to run.

Please could you try out the above to see if it gets you started.
